services:
  db:
    container_name: colir.postgres
    image: postgres:16
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: colir
    networks:
      - colir
  backend:
    container_name: colir.backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=colir.postgres
      - DB_NAME=colir
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - 7700:7700
    volumes:
      - attachments:/app/wwwroot/RoomFiles
    depends_on:
      - db
    networks:
      - colir

networks:
  colir:
    driver: bridge

volumes:
  db_data:
  attachments: